services:
#  book:
#    image: book:0.0.1-SNAPSHOT
#    environment:
##      ELASTIC_APM_ENABLED: false
##      APPLICATION_SAIKUL_PAY_BASE_URL: https://ep-test.saikul.com/api
#      SERVER_SERVLET_CONTEXT_PATH: /api
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: rootroot
#      SPRING_FLYWAY_USER: root
#      SPRING_FLYWAY_PASSWORD: rootroot
##      SPRING_RABBITMQ_HOST: rabbitmq
##      SPRING_DATA_REDIS_HOST: redis
#    ports:
#      - 8098:8099
#    networks:
#      - network
#    links:
#      - postgres
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: rootroot
      POSTGRES_USER: root
    ports:
      - 5432:5432
    networks:
      - network
  pgadmin:
    container_name: pgadmin4_01
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: 473380917@qq.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    links:
      - postgres
    networks:
      - network
    ports:
      - 5050:80

networks:
  network:
    driver: bridge