spring:
  main:
    allow-circular-references: true
  application:
    name: book01
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: rootroot
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:db/migration
    ##??Flyway??????? ??clean-disabled=true
    #    clean-disabled: true
    #    out-of-order: true
    ##??????????Flyway,?????????????baseline-on-migrate=true
    #    baseline-on-migrate: true
    ##??baseline???? V1__BaseLine.sql
#    baseline-version: 1
#    driver-class-name: org.postgresql.Driver
  mail:
    # 比如：使用qq邮箱服务(也可以其他服务)
    host: smtp.qq.com
    port: 465
    #发送方的邮箱

    username: 473380917@qq.com
    # 设置密码，该处的密码是发送方QQ邮箱开启SMTP的授权码而非QQ密码
    password: gycqdrxgizazbiie
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379



#  password=password
server:
  port: 8099
  servlet:
    context-path: /api
logging:
  level:
    root: DEBUG

jwt:
  secret: I2ddU/A51ZqBrePymscViPmiGZNIrjSjKcX+YowurDc=
  expiration: 43200000 # 12 hour


custom:
  invite-register:
    code-timeout: 30
    code-length: 8
    register-link: http://localhost:8000/register
  user-validate:
    code-timeout: 5
    code-length: 6
  book:
    borrowing:
      default-days: 45
      max-days: 90

springdoc:
  api-docs:
    path: /api-docs

#  minio.url=http://localhost:9000
#  minio.access-key=minio
#  minio.secret-key=minio123

# 将如上minio 转换为yml语法
minio:
  url: http://oss.makkapakka.cn:9000
  access-key: minio
  secret-key: minio123
  bucket-name: book01
  expiration: 3600000 # 1 hour
  region: us-east-1
  endpoint: http://oss.makkapakka.cn:9000
