/*给files 和books_files添加上创建日期、修改日期、是否删除字段*/
ALTER TABLE files ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE files ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE files ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE books_files ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE books_files ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE books_files ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE;

